/**
 * Database Seeder
 * Populates DB with realistic mock Valorant players for development/demo
 * Run with: npm run seed
 */

require('dotenv').config();
const mongoose = require('mongoose');
const User = require('../models/User');

const MOCK_PLAYERS = [
  // ── Females ──────────────────────────────────────────────────────────────────
  {
    username: 'AyeshaFrags',
    email: 'ayesha@demo.com',
    password: 'password123',
    gender: 'Female',
    age: 20,
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    rank: 'Immortal 1',
    region: 'Maharashtra',
    city: 'Mumbai',
    roles: ['Duelist', 'Initiator'],
    playstyleTags: ['Competitive', 'Aggressive'],
    voiceChatPreference: 'required',
    bio: 'Jett/Neon main from Mumbai. Entry fragger with 300+ hrs. Looking for serious ranked duo, Immortal+.',
    preferredRankMin: 'Diamond 3',
    preferredRankMax: 'Radiant',
    favoriteAgents: ['Jett', 'Neon', 'Raze'],
    riotId: { gameName: 'AyeshaFrags', tagLine: 'IN1' },
    isProfileComplete: true,
  },
  {
    username: 'PriyaViper',
    email: 'priya@demo.com',
    password: 'password123',
    gender: 'Female',
    age: 22,
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    rank: 'Diamond 2',
    region: 'Karnataka',
    city: 'Bengaluru',
    roles: ['Controller', 'Sentinel'],
    playstyleTags: ['Tactical', 'Competitive'],
    voiceChatPreference: 'preferred',
    bio: 'Viper/Cypher main. IGL background, love setting up post-plants. Bengaluru based, play 9pm–1am.',
    preferredRankMin: 'Diamond 1',
    preferredRankMax: 'Immortal 3',
    favoriteAgents: ['Viper', 'Cypher', 'Killjoy'],
    riotId: { gameName: 'PriyaViper', tagLine: 'IN1' },
    isProfileComplete: true,
  },
  {
    username: 'ZaraSkye',
    email: 'zara@demo.com',
    password: 'password123',
    gender: 'Female',
    age: 19,
    avatar: 'https://randomuser.me/api/portraits/women/26.jpg',
    rank: 'Platinum 3',
    region: 'Delhi',
    city: 'New Delhi',
    roles: ['Initiator', 'Flex'],
    playstyleTags: ['Chill', 'Casual'],
    voiceChatPreference: 'optional',
    bio: 'Skye/Fade main. Casual-competitive player, just want consistent teammates who don\'t flame 😅',
    preferredRankMin: 'Gold 3',
    preferredRankMax: 'Diamond 1',
    favoriteAgents: ['Skye', 'Fade', 'Sova'],
    riotId: { gameName: 'ZaraSkye', tagLine: 'IN2' },
    isProfileComplete: true,
  },
  {
    username: 'NehaGecko',
    email: 'neha@demo.com',
    password: 'password123',
    gender: 'Female',
    age: 23,
    avatar: 'https://randomuser.me/api/portraits/women/57.jpg',
    rank: 'Gold 2',
    region: 'Tamil Nadu',
    city: 'Chennai',
    roles: ['Initiator', 'Duelist'],
    playstyleTags: ['Casual', 'Chill'],
    voiceChatPreference: 'optional',
    bio: 'Chennai gamer, Gekko/Phoenix main. Silver→Gold grind done, aiming Plat. Fun duo > sweaty 5-stack.',
    preferredRankMin: 'Silver 3',
    preferredRankMax: 'Platinum 2',
    favoriteAgents: ['Gekko', 'Phoenix', 'Breach'],
    riotId: { gameName: 'NehaGecko', tagLine: 'IN3' },
    isProfileComplete: true,
  },
  {
    username: 'IshaSentinel',
    email: 'isha@demo.com',
    password: 'password123',
    gender: 'Female',
    age: 21,
    avatar: 'https://randomuser.me/api/portraits/women/33.jpg',
    rank: 'Ascendant 2',
    region: 'Telangana',
    city: 'Hyderabad',
    roles: ['Sentinel', 'Controller'],
    playstyleTags: ['Competitive', 'Tactical'],
    voiceChatPreference: 'required',
    bio: 'Killjoy/Sage main from Hyderabad. Ascendant grind, looking for a strategic duo who coms properly.',
    preferredRankMin: 'Ascendant 1',
    preferredRankMax: 'Immortal 2',
    favoriteAgents: ['Killjoy', 'Sage', 'Chamber'],
    riotId: { gameName: 'IshaSentinel', tagLine: 'IN1' },
    isProfileComplete: true,
  },
  {
    username: 'RiyaOmen',
    email: 'riya@demo.com',
    password: 'password123',
    gender: 'Female',
    age: 24,
    avatar: 'https://randomuser.me/api/portraits/women/82.jpg',
    rank: 'Silver 3',
    region: 'West Bengal',
    city: 'Kolkata',
    roles: ['Controller'],
    playstyleTags: ['Casual', 'Chill'],
    voiceChatPreference: 'never',
    bio: 'Omen one-trick from Kolkata. Text only, low pressure games. Learning lineups, patient duo appreciated!',
    preferredRankMin: 'Silver 1',
    preferredRankMax: 'Gold 3',
    favoriteAgents: ['Omen', 'Astra', 'Brimstone'],
    riotId: { gameName: 'RiyaOmen', tagLine: 'IN2' },
    isProfileComplete: true,
  },

  // ── Males ─────────────────────────────────────────────────────────────────────
  {
    username: 'ArjunRaze',
    email: 'arjun@demo.com',
    password: 'password123',
    gender: 'Male',
    age: 21,
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    rank: 'Immortal 3',
    region: 'Maharashtra',
    city: 'Pune',
    roles: ['Duelist'],
    playstyleTags: ['Aggressive', 'Competitive'],
    voiceChatPreference: 'required',
    bio: 'Peaked Radiant last act. Raze/Jett main. Pune based. Grinding back to top. IGL welcome.',
    preferredRankMin: 'Immortal 1',
    preferredRankMax: 'Radiant',
    favoriteAgents: ['Raze', 'Jett', 'Iso'],
    riotId: { gameName: 'ArjunRaze', tagLine: 'IN1' },
    isProfileComplete: true,
  },
  {
    username: 'KaranIGL',
    email: 'karan@demo.com',
    password: 'password123',
    gender: 'Male',
    age: 23,
    avatar: 'https://randomuser.me/api/portraits/men/45.jpg',
    rank: 'Diamond 3',
    region: 'Delhi',
    city: 'New Delhi',
    roles: ['Controller', 'Initiator'],
    playstyleTags: ['Tactical', 'Competitive', 'IGL'],
    voiceChatPreference: 'required',
    bio: 'IGL main. Brimstone/Sova — setting up plays, not just fragging. Delhi based, need a duo who listens.',
    preferredRankMin: 'Diamond 2',
    preferredRankMax: 'Immortal 3',
    favoriteAgents: ['Brimstone', 'Sova', 'Omen'],
    riotId: { gameName: 'KaranIGL', tagLine: 'IN1' },
    isProfileComplete: true,
  },
  {
    username: 'RohanChamber',
    email: 'rohan@demo.com',
    password: 'password123',
    gender: 'Male',
    age: 20,
    avatar: 'https://randomuser.me/api/portraits/men/77.jpg',
    rank: 'Platinum 2',
    region: 'Gujarat',
    city: 'Ahmedabad',
    roles: ['Sentinel', 'Duelist'],
    playstyleTags: ['Competitive', 'Casual'],
    voiceChatPreference: 'preferred',
    bio: 'Chamber/Killjoy from Ahmedabad. Plat grind, looking for someone to push Diamond with.',
    preferredRankMin: 'Gold 3',
    preferredRankMax: 'Diamond 1',
    favoriteAgents: ['Chamber', 'Killjoy', 'Jett'],
    riotId: { gameName: 'RohanChamber', tagLine: 'IN2' },
    isProfileComplete: true,
  },
  {
    username: 'DevFade',
    email: 'dev@demo.com',
    password: 'password123',
    gender: 'Male',
    age: 19,
    avatar: 'https://randomuser.me/api/portraits/men/12.jpg',
    rank: 'Gold 1',
    region: 'Rajasthan',
    city: 'Jaipur',
    roles: ['Initiator', 'Flex'],
    playstyleTags: ['Chill', 'Casual'],
    voiceChatPreference: 'optional',
    bio: 'Fade/Skye main. Jaipur gamer, play after college hours. Chill vibes only, no rage please.',
    preferredRankMin: 'Silver 2',
    preferredRankMax: 'Platinum 1',
    favoriteAgents: ['Fade', 'Skye', 'Gekko'],
    riotId: { gameName: 'DevFade', tagLine: 'IN3' },
    isProfileComplete: true,
  },
  {
    username: 'SarthakNeon',
    email: 'sarthak@demo.com',
    password: 'password123',
    gender: 'Male',
    age: 22,
    avatar: 'https://randomuser.me/api/portraits/men/55.jpg',
    rank: 'Ascendant 1',
    region: 'Karnataka',
    city: 'Bengaluru',
    roles: ['Duelist', 'Initiator'],
    playstyleTags: ['Aggressive', 'Competitive'],
    voiceChatPreference: 'preferred',
    bio: 'Neon/Raze main. Fast aggressive playstyle. Blore tech bro by day, Valorant grinder by night.',
    preferredRankMin: 'Diamond 3',
    preferredRankMax: 'Immortal 3',
    favoriteAgents: ['Neon', 'Raze', 'Breach'],
    riotId: { gameName: 'SarthakNeon', tagLine: 'IN1' },
    isProfileComplete: true,
  },
  {
    username: 'VikramViper',
    email: 'vikram@demo.com',
    password: 'password123',
    gender: 'Male',
    age: 25,
    avatar: 'https://randomuser.me/api/portraits/men/88.jpg',
    rank: 'Diamond 1',
    region: 'Punjab',
    city: 'Chandigarh',
    roles: ['Controller', 'Sentinel'],
    playstyleTags: ['Tactical', 'Competitive', 'IGL'],
    voiceChatPreference: 'required',
    bio: 'Viper/Cypher wall lineups nerd. Chandigarh. Will call every util if you let me IGL. D1 duo wanted.',
    preferredRankMin: 'Diamond 1',
    preferredRankMax: 'Immortal 2',
    favoriteAgents: ['Viper', 'Cypher', 'Sage'],
    riotId: { gameName: 'VikramViper', tagLine: 'IN2' },
    isProfileComplete: true,
  },
  {
    username: 'AaravClove',
    email: 'aarav@demo.com',
    password: 'password123',
    gender: 'Male',
    age: 18,
    avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    rank: 'Silver 1',
    region: 'Uttar Pradesh',
    city: 'Lucknow',
    roles: ['Controller', 'Flex'],
    playstyleTags: ['Casual', 'Chill'],
    voiceChatPreference: 'optional',
    bio: 'Just started a few months ago. Clove main, loving the controller life. Need a patient and fun duo!',
    preferredRankMin: 'Iron 1',
    preferredRankMax: 'Gold 1',
    favoriteAgents: ['Clove', 'Omen', 'Brimstone'],
    riotId: { gameName: 'AaravClove', tagLine: 'IN3' },
    isProfileComplete: true,
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/find-your-duo');
    console.log('✅ Connected to MongoDB');

    // Clear existing mock users (only demo accounts)
    await User.deleteMany({ email: { $regex: '@demo.com$' } });
    console.log('🧹 Cleared existing seed data');

    // Insert mock players
    const created = await User.create(MOCK_PLAYERS);
    console.log(`🌱 Seeded ${created.length} players:`);
    created.forEach((u) => console.log(`   • ${u.username} (${u.gender}, ${u.rank}, ${u.region})`));

    console.log('\n✅ Database seeded successfully!');
    console.log('🔑 All demo accounts use password: password123\n');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seed error:', error);
    process.exit(1);
  }
};

seed();
